//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvgPatternGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SvgTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SvgTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SvgPatternGenerator.SvgTemplates", typeof(SvgTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&apos;http://www.w3.org/2000/svg&apos; width=&apos;15&apos; height=&apos;15&apos;&gt;
        ///	&lt;rect width=&apos;50&apos; height=&apos;50&apos; fill=&apos;{0}&apos; /&gt;
        ///	&lt;circle cx=&apos;3&apos; cy=&apos;4.3&apos; r=&apos;1.8&apos; fill=&apos;{1}&apos; /&gt;
        ///	&lt;circle cx=&apos;3&apos; cy=&apos;3&apos; r=&apos;1.8&apos; fill=&apos;{2}&apos; /&gt;
        ///	&lt;circle cx=&apos;10.5&apos; cy=&apos;12.5&apos; r=&apos;1.8&apos; fill=&apos;{1}&apos; /&gt;
        ///	&lt;circle cx=&apos;10.5&apos; cy=&apos;11.3&apos; r=&apos;1.8&apos; fill=&apos;{2}&apos; /&gt;
        ///&lt;/svg&gt;
        ///.
        /// </summary>
        internal static string CarbonFibre {
            get {
                return ResourceManager.GetString("CarbonFibre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&apos;http://www.w3.org/2000/svg&apos; xmlns:xlink=&apos;http://www.w3.org/1999/xlink&apos; width=&apos;60&apos; height=&apos;30&apos;&gt;
        ///	&lt;defs&gt;
        ///		&lt;rect id=&apos;r&apos; width=&apos;30&apos; height=&apos;15&apos; fill=&apos;{0}&apos; stroke-width=&apos;2.5&apos; stroke=&apos;{1}&apos; /&gt;
        ///		&lt;g id=&apos;p&apos;&gt;
        ///			&lt;use xlink:href=&apos;#r&apos; /&gt;
        ///			&lt;use y=&apos;15&apos; xlink:href=&apos;#r&apos; /&gt;
        ///			&lt;use y=&apos;30&apos; xlink:href=&apos;#r&apos; /&gt;
        ///			&lt;use y=&apos;45&apos; xlink:href=&apos;#r&apos; /&gt;
        ///		&lt;/g&gt;
        ///	&lt;/defs&gt;
        ///	&lt;use xlink:href=&apos;#p&apos; transform=&apos;translate(0 -25) skewY(40)&apos; /&gt;
        ///	&lt;use xlink:href=&apos;#p&apos; transform=&apos;translate(30 0) skewY(-40)&apos; /&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string Chevrons {
            get {
                return ResourceManager.GetString("Chevrons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&apos;http://www.w3.org/2000/svg&apos; width=&apos;70&apos; height=&apos;70&apos;&gt;
        ///	&lt;rect width=&apos;70&apos; height=&apos;70&apos; fill=&apos;{0}&apos; /&gt;
        ///	&lt;g transform=&apos;rotate(45)&apos;&gt;
        ///		&lt;rect width=&apos;99&apos; height=&apos;25&apos; fill=&apos;{1}&apos; /&gt;
        ///		&lt;rect y=&apos;-50&apos; width=&apos;99&apos; height=&apos;25&apos; fill=&apos;{1}&apos; /&gt;
        ///	&lt;/g&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string DiagonalStripes {
            get {
                return ResourceManager.GetString("DiagonalStripes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&apos;http://www.w3.org/2000/svg&apos; width=&apos;56&apos; height=&apos;100&apos;&gt;
        ///	&lt;rect width=&apos;56&apos; height=&apos;100&apos; fill=&apos;{0}&apos; /&gt;
        ///	&lt;path d=&apos;M28 66L0 50L0 16L28 0L56 16L56 50L28 66L28 100&apos; fill=&apos;none&apos; stroke=&apos;{1}&apos; stroke-width=&apos;2&apos; /&gt;
        ///	&lt;path d=&apos;M28 0L28 34L0 50L0 84L28 100L56 84L56 50L28 34&apos; fill=&apos;none&apos; stroke=&apos;{2}&apos; stroke-width=&apos;2&apos; /&gt;
        ///&lt;/svg&gt;
        ///.
        /// </summary>
        internal static string Honeycomb {
            get {
                return ResourceManager.GetString("Honeycomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&apos;http://www.w3.org/2000/svg&apos; width=&apos;30&apos; height=&apos;30&apos;&gt;
        ///	&lt;rect width=&apos;30&apos; height=&apos;30&apos; fill=&apos;{0}&apos; /&gt;
        ///	&lt;rect width=&apos;30&apos; height=&apos;18&apos; fill=&apos;{1}&apos; /&gt;
        ///&lt;/svg&gt;
        ///.
        /// </summary>
        internal static string HorizontalStripes {
            get {
                return ResourceManager.GetString("HorizontalStripes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&apos;http://www.w3.org/2000/svg&apos; width=&apos;40&apos; height=&apos;40&apos; viewBox=&apos;0 0 20 20&apos;&gt;
        ///	&lt;rect width=&apos;40&apos; height=&apos;40&apos; fill=&apos;{0}&apos; /&gt;
        ///	&lt;circle r=&apos;9.2&apos; stroke-width=&apos;1&apos; stroke=&apos;{1}&apos; fill=&apos;none&apos; /&gt;
        ///	&lt;circle cy=&apos;18.4&apos; r=&apos;9.2&apos; stroke-width=&apos;1px&apos; stroke=&apos;{1}&apos; fill=&apos;none&apos; /&gt;
        ///	&lt;circle cx=&apos;18.4&apos; cy=&apos;18.4&apos; r=&apos;9.2&apos; stroke-width=&apos;1&apos; stroke=&apos;{1}&apos; fill=&apos;none&apos; /&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string MicrobialMat {
            get {
                return ResourceManager.GetString("MicrobialMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&apos;http://www.w3.org/2000/svg&apos; width=&apos;50&apos; height=&apos;50&apos;&gt;
        ///	&lt;rect width=&apos;50&apos; height=&apos;50&apos; fill=&apos;{0}&apos; /&gt;
        ///	&lt;rect x=&apos;25&apos; width=&apos;25&apos; height=&apos;50&apos; fill=&apos;{1}&apos; /&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string VerticalStripes {
            get {
                return ResourceManager.GetString("VerticalStripes", resourceCulture);
            }
        }
    }
}
